#ifndef RESOURCE_H
#define RESOURCE_H

#define ID_BOARD_WINDOW 2
#define ID_TEST_WINDOW 3

#define IDR_REVERSI_MENU 101

#define IDM_FILE_EXIT 9001
#define IDM_FILE_TEST 9002
#define IDM_FILE_NEW 9003

#define WM_SET_TOKEN (WM_USER + 1)

#endif //RESOURCE_H
